version: "2"

# make sure to change the domain name before
# running docker-compose
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/etc/:/etc/prometheus/
      - ./prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - default
    restart: always
    user: "65534"

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana/data/:/var/lib/grafana/
    environment:
      # possible config options:
      # https://grafana.com/docs/grafana/latest/administration/configuration/#configure-with-environment-variables
      GF_SERVER_DOMAIN: "grafana.example.com"
      GF_ANALYTICS_REPORTING_ENABLED: "false"
      GF_SECURITY_COOKIE_SECURE: "true"
      GF_USERS_ALLOW_SIGN_UP: "false"
    networks:
      - default
    user: "65534"
    restart: always

  caddy:
    image: caddy:latest
    volumes:
      - ./caddy/data:/data
      - ./caddy/config:/config
    ports:
      - 80:80
      - 443:443
    command: caddy reverse-proxy --from grafan.example.com --to grafana:3000
    networks:
      - default
    depends_on:
      - grafana
    user: "65534"
    restart: always
